// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shared.Data;

#nullable disable

namespace Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstSurname")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("first_surname");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hashed_password");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("SecondSurname")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("second_surname");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("SurnameFirst")
                        .HasColumnType("boolean")
                        .HasColumnName("surname_first");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_user_status");

                    b.ToTable("user", "auth", t =>
                        {
                            t.HasCheckConstraint("user_email_format_chk", "position('@' in email) > 1");
                        });
                });

            modelBuilder.Entity("Shared.Entities.Chat.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_conversation_created_by_user_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_conversation_type");

                    b.ToTable("conversation", "chat", t =>
                        {
                            t.HasCheckConstraint("conversation_name_required_for_channels_chk", "(\r\n                    type IN ('channel', 'private_channel')\r\n                    AND name IS NOT NULL\r\n                    AND btrim(name) <> ''\r\n                )\r\n                OR\r\n                (\r\n                    type IN ('direct_message', 'group_message')\r\n                )");
                        });
                });

            modelBuilder.Entity("Shared.Entities.Chat.ConversationMember", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_read_at");

                    b.Property<Guid?>("LastReadMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_read_message_id");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<DateTime?>("MutedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("muted_until");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("ConversationId", "LastReadMessageId");

                    b.HasIndex("ConversationId", "LeftAt")
                        .HasDatabaseName("idx_conversation_member_conversation_left_at");

                    b.HasIndex("UserId", "ConversationId")
                        .HasDatabaseName("idx_conversation_member_user_conversation");

                    b.ToTable("conversation_member", "chat", t =>
                        {
                            t.HasCheckConstraint("conversation_member_read_time_chk", "last_read_at IS NULL OR last_read_at >= joined_at");
                        });
                });

            modelBuilder.Entity("Shared.Entities.Chat.DirectMessageKey", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("UserPairKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_pair_key");

                    b.HasKey("ConversationId");

                    b.HasIndex("UserPairKey")
                        .IsUnique();

                    b.ToTable("direct_message_key", "chat", t =>
                        {
                            t.HasCheckConstraint("dm_pair_key_not_empty_chk", "btrim(user_pair_key) <> ''");
                        });
                });

            modelBuilder.Entity("Shared.Entities.Chat.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_message_id");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentMessageId")
                        .HasDatabaseName("idx_message_parent_message_id");

                    b.HasIndex("SenderUserId")
                        .HasDatabaseName("idx_message_sender_user_id");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_message_conversation_created_at");

                    b.HasIndex("ConversationId", "Id")
                        .IsUnique()
                        .HasDatabaseName("uq_message_conversation_id_id");

                    b.ToTable("message", "chat", t =>
                        {
                            t.HasCheckConstraint("message_not_own_parent_chk", "parent_message_id IS NULL OR parent_message_id <> id");

                            t.HasCheckConstraint("text_message_requires_body_chk", "type <> 'text' OR (body IS NOT NULL AND btrim(body) <> '')");
                        });
                });

            modelBuilder.Entity("Shared.Entities.Chat.MessageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("storage_url");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("idx_message_attachment_message_id");

                    b.ToTable("message_attachment", "chat", t =>
                        {
                            t.HasCheckConstraint("attachment_size_positive_chk", "size_bytes > 0");
                        });
                });

            modelBuilder.Entity("Shared.Entities.Chat.Conversation", b =>
                {
                    b.HasOne("Shared.Entities.Auth.User", "CreatedByUser")
                        .WithMany("CreatedConversations")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_users_created_by_user_id");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Shared.Entities.Chat.ConversationMember", b =>
                {
                    b.HasOne("Shared.Entities.Chat.Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_members_conversations_conversation_id");

                    b.HasOne("Shared.Entities.Auth.User", "User")
                        .WithMany("ConversationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_members_users_user_id");

                    b.HasOne("Shared.Entities.Chat.Message", "LastReadMessage")
                        .WithMany("MembersWhoRead")
                        .HasForeignKey("ConversationId", "LastReadMessageId")
                        .HasPrincipalKey("ConversationId", "Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_conversation_members__messages_last_read_message_id");

                    b.Navigation("Conversation");

                    b.Navigation("LastReadMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Entities.Chat.DirectMessageKey", b =>
                {
                    b.HasOne("Shared.Entities.Chat.Conversation", "Conversation")
                        .WithOne("DirectMessageKey")
                        .HasForeignKey("Shared.Entities.Chat.DirectMessageKey", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direct_message_keys_conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Shared.Entities.Chat.Message", b =>
                {
                    b.HasOne("Shared.Entities.Chat.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");

                    b.HasOne("Shared.Entities.Chat.Message", "ParentMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_messages_messages_parent_message_id");

                    b.HasOne("Shared.Entities.Auth.User", "SenderUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_sender_user_id");

                    b.Navigation("Conversation");

                    b.Navigation("ParentMessage");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Shared.Entities.Chat.MessageAttachment", b =>
                {
                    b.HasOne("Shared.Entities.Chat.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_attachments_messages_message_id");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Shared.Entities.Auth.User", b =>
                {
                    b.Navigation("ConversationMemberships");

                    b.Navigation("CreatedConversations");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("Shared.Entities.Chat.Conversation", b =>
                {
                    b.Navigation("DirectMessageKey");

                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Shared.Entities.Chat.Message", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("MembersWhoRead");

                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
